// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBbbfvSbTJ1M-7TtwoSmZjwNi_eSFYP-I',
    appId: '1:124653338972:web:6330396757ee4ce1df8199',
    messagingSenderId: '124653338972',
    projectId: 'app-games-e8fd5',
    authDomain: 'app-games-e8fd5.firebaseapp.com',
    storageBucket: 'app-games-e8fd5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9osFUlbJ-_svO_JFT-ttijDk5aI81fL0',
    appId: '1:124653338972:android:c7f61b3ea66d3afbdf8199',
    messagingSenderId: '124653338972',
    projectId: 'app-games-e8fd5',
    storageBucket: 'app-games-e8fd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxIaD42wu1L6ursu8TT0T2QyMCOOzWf34',
    appId: '1:124653338972:ios:f75cc5c0bfd433a0df8199',
    messagingSenderId: '124653338972',
    projectId: 'app-games-e8fd5',
    storageBucket: 'app-games-e8fd5.firebasestorage.app',
    iosBundleId: 'com.example.appGames',
  );
}
